import Head from "next/head";
import styled from "styled-components";

import groq from "groq";
import client from "../../client-config";

import Menu from "../../components/Menu/menu";
import ContactInformation from "../../components/Contact-Information/contact-information";

import { MainContainer } from "../index";
import { TopContainer, Heading } from "../projects";

export default function Project({ project }) {
  console.log(project);
  return (
    <>
      <Head>
        <title>New Work Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <TopContainer>
          <Heading>{project?.title}</Heading>
          <Menu></Menu>
        </TopContainer>

        <ContactInformation></ContactInformation>
      </MainContainer>
    </>
  );
}

export async function getStaticPaths() {
  const paths = await client.fetch(
    groq`*[_type == "projects" && defined(slug.current)][].slug.current`
  );

  return {
    paths: paths.map((slug) => ({ params: { slug } })),
    fallback: true,
  };
}

export async function getStaticProps(context) {
  const { slug = "" } = context.params;
  const project = await client.fetch(
    groq`*[_type == "projects" && slug.current == "${slug}"]`
  );

  return {
    props: {
      project: project[0],
    },
  };
}
