import Head from "next/head";
import styled from "styled-components";

import groq from "groq";
import client from "../../client-config";

import Menu from "../../components/Menu/menu";
import Carousel from "../../components/Carousel/carousel";
import TitleLink from "../../components/Title-Link/title-link";

import { MainContainer } from "../index";
import { TopContainer, Heading } from "../projects";

const DescriptionText = styled.div`
  width: 50%;
  position: absolute;
  top: 13rem;
  left: 10rem;

  @media (max-width: 600px) {
    left: 3rem;
  }
`;

export default function Project({ data }) {
  return (
    <>
      <Head>
        <title>New Work Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <TitleLink top={true} href="/"></TitleLink>
        <TopContainer>
          <Heading>{data?.title}</Heading>
          <Menu></Menu>
        </TopContainer>
        <DescriptionText>
          <p>{data?.description}</p>
        </DescriptionText>
        <Carousel slides={data?.images}></Carousel>
        <TitleLink href="/"></TitleLink>
      </MainContainer>
    </>
  );
}

export async function getStaticPaths() {
  const paths = await client.fetch(
    groq`*[_type == "collabrators" && defined(slug.current)][].slug.current`
  );

  return {
    paths: paths.map((slug) => ({ params: { slug } })),
    fallback: true,
  };
}

export async function getStaticProps(context) {
  const { slug = "" } = context.params;
  const data = await client.fetch(
    groq`*[_type == "collabrators" && slug.current == "${slug}"]`
  );

  return {
    props: {
      data: data[0],
    },
  };
}
