import Head from "next/head";
import groq from "groq";
import client from "../client-config";

import PageTemplate from "../components/Page-Template/page-template";

export default function Collabrators({ collaborators }) {
  return (
    <>
      <Head>
        <title>Collaborators | Tim Nees Architects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTemplate
        heading="collaborators"
        type="collaborators"
        data={collaborators}
        active="collaborators"
      ></PageTemplate>
    </>
  );
}

export async function getStaticProps() {
  const collaborators = await client.fetch(groq`*[_type == "collaborators"]`);
  return {
    props: {
      collaborators,
    },
  };
}
