import Head from "next/head";
import groq from "groq";
import client from "../client-config";

import Menu from "../components/Menu/menu";
import ContactInformation from "../components/Contact-Information/contact-information";

import { MainContainer } from "./index";
import { Heading, TopContainer } from "./projects";
import ImageLinks from "../components/Image-Links/image-links";
import TitleLink from "../components/Title-Link/title-link";

export default function Collabrators({ collabrators }) {
  return (
    <>
      <Head>
        <title>New Work Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <TitleLink top={true} href="/"></TitleLink>
        <TopContainer>
          <Heading>collabrators</Heading>
          <Menu></Menu>
        </TopContainer>
        <ImageLinks projects={collabrators}></ImageLinks>

        <ContactInformation></ContactInformation>
        <TitleLink href="/"></TitleLink>
      </MainContainer>
    </>
  );
}

export async function getStaticProps() {
  const collabrators = await client.fetch(groq`*[_type == "collabrators"]`);
  return {
    props: {
      collabrators,
    },
  };
}
