import Head from "next/head";
import groq from "groq";
import client from "../client-config";

import PageTemplate from "../components/Page-Template/page-template";

export default function Projects({ projects }) {
  return (
    <>
      <Head>
        <title>Projects | Tim Nees Architects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTemplate
        heading="projects"
        type="projects"
        data={projects}
        archiveLink={true}
        active="projects"
      ></PageTemplate>
    </>
  );
}

export async function getStaticProps() {
  const projects = await client.fetch(
    groq`*[_type == "projects"][0..5]  | order(_createdAt desc)`
  );
  return {
    props: {
      projects,
    },
  };
}
